Fix jobs to queue metric
Expensify/Bedrock-PHP pull request #149
Opened 2020-08-20 13:05 UTC by justinpersaud

2020-08-20 18:30 UTC, iwiznia requested changes

2020-08-20 18:30 UTC, iwiznia commented on bin/BedrockWorkerManager.php
> +            $stats->timer("bedrockWorkerManager.fullLoop", microtime(true) - $loopStartTime); /* @phan-suppress-current-line PhanTypeMismatchArgument */
Why the suppress? What was the error? I bet it can be fixed by casting the 2nd param to int, which is what timer expects

2020-08-20 18:30 UTC, iwiznia commented on bin/BedrockWorkerManager.php
> +                $stats->timer('bedrockWorkerManager.numberOfJobsToQueue', $jobsToQueue);
lol copy pasta error since years ago 😂

2020-08-20 18:30 UTC, iwiznia commented on bin/BedrockWorkerManager.php
> +            $stats->timer("bedrockWorkerManager.fullLoop", microtime(true) - $loopStartTime); /* @phan-suppress-current-line PhanTypeMismatchArgument */
We don't have the style checker in this repo, can you change the quotes to single quotes? A bit nitpicky but since you need to change this line anyway...

2020-08-20 18:30 UTC, iwiznia commented on bin/BedrockWorkerManager.php
> +        /* @phan-suppress-next-line PhanTypeArraySuspiciousNullable */
Phan, too stupid to realize this can never be null 🤦

2020-08-20 18:30 UTC, iwiznia commented on bin/BedrockWorkerManager.php
> +        /* @phan-suppress-next-line PhanTypeArraySuspiciousNullable */
Since you added this to 3 places, what about doing something like:
```
$response = $response ?? [];
```
Then we should be able to remove all the suppress you added.
Alternatively, use `??` in all the places we use it, ie: `if (($response['code'] ?? null) == 200)`

2020-08-20 18:39 UTC, justinpersaud commented on bin/BedrockWorkerManager.php
> +            $stats->timer("bedrockWorkerManager.fullLoop", microtime(true) - $loopStartTime); /* @phan-suppress-current-line PhanTypeMismatchArgument */
Oh, this one complains about the type on the interface. It expects a `int` but `microtime` returns a float. In the statsd class, this can take int or float because it rounds the number. I tried changing the interface to accept `number` but that didn't work, is there a better solution?

2020-08-20 18:53 UTC, iwiznia commented on bin/BedrockWorkerManager.php
> +            $stats->timer("bedrockWorkerManager.fullLoop", microtime(true) - $loopStartTime); /* @phan-suppress-current-line PhanTypeMismatchArgument */
`StatsInterface` has it as int, so I guess you can update that one and the error will go away

2020-08-20 19:04 UTC, justinpersaud commented
updated

2020-08-20 19:05 UTC, iwiznia approved these changes
You need to create the version

2020-08-20 19:23 UTC, justinpersaud commented
I have the tag here already, for the next part, do we just bump the version in Web-Expensify composer file?

2020-08-24 14:29 UTC, merged

2020-08-24 14:29 UTC, justinpersaud commented
I am self merging this because the web-PR was merged.