Log RetryableException message
Expensify/Bedrock-PHP pull request #158
Opened 2021-04-02 17:56 UTC by Beamanator

## Details

TL;DR: Logs the `RetryableException`'s `message` when caught in `BedrockWorkerManager.php`.

This is useful so we can have more details about why `RetryableException`s get logged.

## Fixes
$ https://github.com/Expensify/Expensify/issues/159221

2021-04-02 20:05 UTC, iwiznia approved these changes
Nice

2021-04-02 20:07 UTC, iwiznia requested changes

2021-04-02 20:07 UTC, iwiznia commented on bin/BedrockWorkerManager.php
> +                                    'message' => $e->getMessage(),
Oh wait, I think if you pass the exception itself, we will get a better log due to [this](https://github.com/Expensify/Web-Expensify/blob/c729db021a461171810812bf0ca1612ac64d348c/lib/Log.php#L515-L518).

2021-04-05 00:19 UTC, jasperhuangg commented on bin/BedrockWorkerManager.php
> +                                    'message' => $e->getMessage(),
+1

2021-04-05 07:26 UTC, Beamanator commented on bin/BedrockWorkerManager.php
> +                                    'message' => $e->getMessage(),
Good catch! I like this better 👍

2021-04-05 07:27 UTC, Beamanator commented
Update: Now logging entire `RetryableException` with `'exception' => $e,`

2021-04-05 17:51 UTC, iwiznia approved these changes

2021-04-07 06:05 UTC, jasperhuangg approved these changes

2021-04-09 00:13 UTC, stitesExpensify approved these changes

2021-04-09 00:13 UTC, merged