Add localjobs params
Expensify/Bedrock-PHP pull request #159
Opened 2021-07-06 21:34 UTC by righdforsa

This adds a locally working version of the BWM script that captures the worker PID as well as the job "retryAfter" setting, so that long-running jobs in prod can be checked to identify what job is running in which pid and whether there is a retryAfter setting. (which means that if we killed it, it would recover automatically)

Fixes https://github.com/Expensify/Expensify/issues/149165

Question:
In this version of the code, the local jobs db handle is used after the fork. Also, the "getLastInsertedID" function is used after the fork. I'm concerned about possible race conditions. LMK if you think we need to revise.  

Tests:
- tested locally with populated retryAfter, worked as expected
- tested locally with unpopulated retryAfter, worked as expected
- tested locally with all  Web-Expensify tests matching "job" (case-insensitive)

<details>
<summary>Web-E tests</summary>
: 2021-07-06 19:52:13 the-platform-2.local:~/source/Expensify/Expensidev$; find Web-Expensify/_tests/ -iname "*job*"
Web-Expensify/_tests//unit/lib/SmartScanDos/SSDosJobTest.php
Web-Expensify/_tests//integration/script/bwm/SmartScanJobManagerTest.php
Web-Expensify/_tests//integration/lib/SmartScanDos/SSDosJobTest.php
Web-Expensify/_tests//integration/lib/ChatBot/AssignableJobFlowsTest.php
Web-Expensify/_tests//integration/lib/Bedrock/ParentJobsTest.php
Web-Expensify/_tests//integration/lib/Bedrock/JobsTest.php
Web-Expensify/_tests//integration/lib/Expensiworks/JobReviewerTest.php
Web-Expensify/_tests//integration/CleanJobsDBTrait.php
: 2021-07-06 19:52:33 the-platform-2.local:~/source/Expensify/Expensidev$; ./script/phpTests.sh _tests//unit/lib/SmartScanDos/SSDosJobTest.php
Running integration tests
PHPUnit 9.5.2 by Sebastian Bergmann and contributors.

	Test 'SSDosJobTest::testGetHitAnswers' took                                                                                                                 0.080 seconds.
.	Test 'SSDosJobTest::testShouldApproveAnswersNoneGold' took                                                                                                  0.012 seconds.
.	Test 'SSDosJobTest::testShouldApproveAnswersSomeGoldNotMatches' took                                                                                        0.397 seconds.
.	Test 'SSDosJobTest::testShouldApproveAnswersSomeGoldMatches' took                                                                                           0.011 seconds.
.	Test 'SSDosJobTest::testMerchantMatching with data set #0 ('Long Merchant Name', 'Long Merchant', true)' took                                               0.004 seconds.
.	Test 'SSDosJobTest::testMerchantMatching with data set #1 ('Long Merchant', 'Long Merchant Name', true)' took                                               0.004 seconds.
.	Test 'SSDosJobTest::testMerchantMatching with data set #2 ('Long', 'Long Merchant Name', false)' took                                                       0.005 seconds.
.	Test 'SSDosJobTest::testMerchantMatching with data set #3 ('Long Merchant Name', 'Long', false)' took                                                       0.005 seconds.
.	Test 'SSDosJobTest::testMerchantMatching with data set #4 ('Mismatched Merchant Name', 'Long Merchant Name', false)' took                                   0.006 seconds.
.	Test 'SSDosJobTest::testMerchantMatching with data set #5 ('Exact Match Merchant Name', 'Exact Match Merchant Name', true)' took                            0.005 seconds.
.	Test 'SSDosJobTest::testCaseAndPunctuation' took                                                                                                            0.011 seconds.
.                                                       11 / 11 (100%)

Time: 00:00.552, Memory: 18.00 MB

OK (11 tests, 12 assertions)
Connection to 127.0.0.1 closed.
: 2021-07-06 19:53:44 the-platform-2.local:~/source/Expensify/Expensidev$; ./script/phpTests.sh _tests//integration/script/bwm/SmartScanJobManagerTest.ph
Running integration tests
^CConnection to 127.0.0.1 closed.
: 2021-07-06 19:53:56 the-platform-2.local:~/source/Expensify/Expensidev$; ./script/phpTests.sh _tests//integration/script/bwm/SmartScanJobManagerTest.php
Running integration tests
PHPUnit 9.5.2 by Sebastian Bergmann and contributors.

	Test 'SmartScanJobManagerTest::testCreateJobsWithPriorities with data set #0 (5, 3, 6, 0)' took                                                             0.231 seconds.
.	Test 'SmartScanJobManagerTest::testCreateJobsWithPriorities with data set #1 (7, 4, 11, 0)' took                                                            0.298 seconds.
.	Test 'SmartScanJobManagerTest::testCreateJobsWithPriorities with data set #2 (40, 10, 11, 0)' took                                                          1.572 seconds.
.	Test 'SmartScanJobManagerTest::testDeleteJobs with data set #0 (5, 3, 1)' took                                                                              0.135 seconds.
.	Test 'SmartScanJobManagerTest::testDeleteJobs with data set #1 (6, 3, 2)' took                                                                              0.663 seconds.
.	Test 'SmartScanJobManagerTest::testDoNotDeleteProcessingRunQueuedJobs' took                                                                                 0.165 seconds.
.                                                              6 / 6 (100%)

Time: 00:03.089, Memory: 12.00 MB

OK (6 tests, 16 assertions)
Connection to 127.0.0.1 closed.
: 2021-07-06 19:54:25 the-platform-2.local:~/source/Expensify/Expensidev$; ./script/phpTests.sh _tests//integration/lib/SmartScanDos/SSDosJobTest.php
Running integration tests
PHPUnit 9.5.2 by Sebastian Bergmann and contributors.

	Test 'SSDosJobTest::testNoGold' took                                                                                                                        0.540 seconds.
.	Test 'SSDosJobTest::testSomeGoldNotMatches' took                                                                                                            0.796 seconds.
.	Test 'SSDosJobTest::testSomeGoldMatches' took                                                                                                               0.141 seconds.
.	Test 'SSDosJobTest::testIllegible' took                                                                                                                     0.239 seconds.
.	Test 'SSDosJobTest::testIllegibleWrongGold' took                                                                                                            0.209 seconds.
.	Test 'SSDosJobTest::testMerchantAnswersWithExtraWhitespace' took                                                                                            0.143 seconds.
.	Test 'SSDosJobTest::testWorkerData' took                                                                                                                    0.176 seconds.
.                                                             7 / 7 (100%)

Time: 00:02.258, Memory: 24.00 MB

OK (7 tests, 24 assertions)
Connection to 127.0.0.1 closed.
: 2021-07-06 21:01:25 the-platform-2.local:~/source/Expensify/Expensidev$; ./script/phpTests.sh _tests//integration/lib/ChatBot/AssignableJobFlowsTest.php
Running integration tests
PHPUnit 9.5.2 by Sebastian Bergmann and contributors.

	Test 'AssignableJobFlowsTest::testSubscribedToActiveChannel' took                                                                                           0.094 seconds.
.	Test 'AssignableJobFlowsTest::testEmptyPusherSubscription' took                                                                                             0.046 seconds.
.	Test 'AssignableJobFlowsTest::testDontAssignToLastResponderIfInactive' took                                                                                 0.568 seconds.
.	Test 'AssignableJobFlowsTest::testAssignToLastResponderFR' took                                                                                            [...]

2021-07-07 04:42 UTC, jasperhuangg commented
Don't have the best understanding of this so I'm going to unrequest myself.

2021-07-07 13:11 UTC, flodnv requested changes
>tested locally with all Web-Expensify tests matching "job"

Do you mean integration tests? Do these use BWM? 😕 

>tested locally with populated retryAfter, worked as expected
>tested locally with unpopulated retryAfter, worked as expected

Do you mean manually?

2021-07-07 13:11 UTC, flodnv commented on bin/BedrockWorkerManager.php
> +        workerPID integer,
NOT NULL?

2021-07-07 13:11 UTC, flodnv commented on bin/BedrockWorkerManager.php
> +        bedrockJobRetry text
`retryAfter`?

2021-07-07 13:11 UTC, flodnv commented on bin/BedrockWorkerManager.php
>          jobID integer NOT NULL,
Does this database get recreated or will we have to make this schema change manually somehow?

2021-07-07 13:11 UTC, flodnv commented on bin/BedrockWorkerManager.php
> +                                $localDB->write("INSERT INTO localJobs (jobID, jobName, started, workerPID, bedrockJobRetry) VALUES ({$job['jobID']}, '{$safeJobName}', ".microtime(true).", {$myPid},
>In this version of the code, the local jobs db handle is used after the fork

I don't think I am following why this change?

2021-07-07 13:11 UTC, flodnv commented on bin/BedrockWorkerManager.php
> +                            $logger->info("got a job and stuffed it in the local db");
lol, is this new log necessary? If so, let's change it to a better message 😄

2021-07-07 13:11 UTC, flodnv commented on bin/BedrockWorkerManager.php
> +                            $safeRetryAfter = array_key_exists('retryAfter', $job) ? SQLite3::escapeString($job['retryAfter']) : "";
I think the array key always exists? In any case, we can do `SQLite3::escapeString($job['retryAfter'] ?? '')`

2021-07-07 17:24 UTC, righdforsa commented
> > tested locally with all Web-Expensify tests matching "job"

> Do you mean integration tests? Do these use BWM? 😕

Good question. I don't know, probably not? I would like to have BWM and localdbs tests for Bedrock-PHP, but it doesn't look like there are any. 

> > tested locally with populated retryAfter, worked as expected
> > tested locally with unpopulated retryAfter, worked as expected

> Do you mean manually?

Yes, tested with local jobs that were created in bedrock. Some with retryAfter set, some without. Both worked as expected. (Jobs ran, retryAfter values were populated into the local DB)

2021-07-07 17:27 UTC, righdforsa commented on bin/BedrockWorkerManager.php
> +        workerPID integer,
NOT NULL breaks if you have an existing table. For most of my testing my first step was to drop the table, but that creates a production dependency. Without "NOT NULL", we can modify the table schema before the deploy rolls out and things should just work.

2021-07-07 17:31 UTC, righdforsa commented on bin/BedrockWorkerManager.php
> +        workerPID integer,
Perhaps setting a default value solves that problem, if we really want the "NOT NULL". I'm ambivalent, but I for sure don't want to have to (stop bwm, drop the table, restart bwm) if we can avoid it.

2021-07-07 17:31 UTC, righdforsa commented on bin/BedrockWorkerManager.php
> +        bedrockJobRetry text
oh, yeah, will fix

2021-07-07 17:33 UTC, righdforsa commented on bin/BedrockWorkerManager.php
>          jobID integer NOT NULL,
It does get recreated if it's missing, but there's no upgrade capability. So, my proposal would be to update the schema before the change goes out.

2021-07-07 17:40 UTC, righdforsa commented on bin/BedrockWorkerManager.php
> +                                $localDB->write("INSERT INTO localJobs (jobID, jobName, started, workerPID, bedrockJobRetry) VALUES ({$job['jobID']}, '{$safeJobName}', ".microtime(true).", {$myPid},
The reason to move the local jobs update is because we should only record jobs we're actually going to run. @iwiznia indicated this was a good idea: https://github.com/Expensify/Expensify/issues/149165#issuecomment-843463567 and suggested it might even fix a longstanding bug: https://github.com/Expensify/Expensify/issues/138250

At a minimum, we could put it after the `if (file_exists($workerFilename)) {` test, ca. line 259, without changing the existing db handles, but then I will have to do a second local db update to write the PID once I have it. (another reason we might not want NOT NULL for the workerPid column)

2021-07-07 17:41 UTC, righdforsa commented on bin/BedrockWorkerManager.php
> +                            $logger->info("got a job and stuffed it in the local db");
🤦 debug message, removing

2021-07-07 17:43 UTC, righdforsa commented on bin/BedrockWorkerManager.php
> +                            $safeRetryAfter = array_key_exists('retryAfter', $job) ? SQLite3::escapeString($job['retryAfter']) : "";
The array key didn't seem to always exist, I was getting a PHP Notice, iirc. Will test your version.

2021-07-07 18:20 UTC, righdforsa commented on bin/BedrockWorkerManager.php
> +                                $localDB->write("INSERT INTO localJobs (jobID, jobName, started, workerPID, bedrockJobRetry) VALUES ({$job['jobID']}, '{$safeJobName}', ".microtime(true).", {$myPid},
It looks like `$localDB` isn't even particularly frequently used. We could close it after the "create table if not exists" statement and then each fork could just open their own copy...if that even matters. The thing I'm more concerned about is the race condition between "insert into" and "get most recently inserted row"...I wonder if wrapping those in a transaction makes sense? Am I making this too complicated?

2021-07-08 11:31 UTC, flodnv commented
Indeed, unfortunately the only way to test BWM changes is manually, AFAIK

2021-07-08 11:32 UTC, flodnv commented on bin/BedrockWorkerManager.php
>          jobID integer NOT NULL,
Yeah that sounds good

2021-07-08 11:32 UTC, flodnv commented on bin/BedrockWorkerManager.php
> +        workerPID integer,
Hmmm maybe this is fine then

2021-07-08 11:32 UTC, flodnv commented
I forgot to ask, why the permissions change on the file?

2021-07-08 11:40 UTC, flodnv commented on bin/BedrockWorkerManager.php
> +                                $localDB->write("INSERT INTO localJobs (jobID, jobName, started, workerPID, bedrockJobRetry) VALUES ({$job['jobID']}, '{$safeJobName}', ".microtime(true).", {$myPid},
Hmmm, I think this is a very valid concern, I'd be curious for @iwiznia's thoughts. However, maybe this isn't a problem: https://www.php.net/manual/en/sqlite3.lastinsertrowid.php#116447

2021-07-08 11:54 UTC, flodnv approved these changes
Tested locally, looks like this is working 👍 Let's make sure to update the schema before deploying this 🙇

2021-07-08 17:22 UTC, righdforsa commented on bin/BedrockWorkerManager.php
> +        workerPID integer,
Well, or maybe I'm being a baby. If we really wanted NOT NULL (which I do think is appropriate for the workerPID column) the only options I can see are a) set a default, or b) stop bwm before manually applying the schema change, then restart, then deploy the code. The latter is what we would do with a bedrock schema change, so maybe I should just suck it up?

2021-07-08 17:26 UTC, righdforsa commented on bin/BedrockWorkerManager.php
> +                                $localDB->write("INSERT INTO localJobs (jobID, jobName, started, workerPID, bedrockJobRetry) VALUES ({$job['jobID']}, '{$safeJobName}', ".microtime(true).", {$myPid},
> Hmmm, I think this is a very valid concern, I'd be curious for @iwiznia's thoughts. However, maybe this isn't a problem: https://www.php.net/manual/en/sqlite3.lastinsertrowid.php#116447

Ah, that's great, so, in that case, I should probably close `$localDB` after the schema check, create a new `$localDB` after the fork, and then we should be fine.

2021-07-08 18:09 UTC, righdforsa commented
> I forgot to ask, why the permissions change on the file?

Good question. I'm not sure what happened here, I hadn't even noticed. Fixed.

2021-07-08 18:12 UTC, righdforsa commented
Updated with a new `$localDB` after the fork, but otherwise leaving the parent `$localDB`. Re-tested locally, still does the expected thing vis-a-vis the local jobs entries.

2021-07-09 11:41 UTC, iwiznia requested changes

2021-07-09 11:41 UTC, iwiznia commented on bin/BedrockWorkerManager.php
> -                    // Close DB connection before forking.
I am a bit lost here... so are we using localDB in both parent and child? And if so, are we closing/reopening the connection before/after forking?

2021-07-09 11:41 UTC, iwiznia commented on bin/BedrockWorkerManager.php
> +                        $localDB = new LocalDB($pathToDB, $logger, $stats);
I don't think we need this as we were not doing it before, it seems what we need is to close and reopen the connection. I _think_ with the current code we are leaking a connection.

2021-07-09 11:41 UTC, iwiznia commented on bin/BedrockWorkerManager.php
> +                            $stats->benchmark('bedrockWorkerManager.db.write.insert', function () use ($localDB, $job, $safeJobName, $safeRetryAfter, $myPid) {
NAB you can simplify this by using arrow functions (which don't need all the `use` variables)

2021-07-09 18:25 UTC, righdforsa commented on bin/BedrockWorkerManager.php
> +                        $localDB = new LocalDB($pathToDB, $logger, $stats);
My assumption had been that by re-instantiating $localDB after the fork, I would get a new local db handle in the local (thread) scope.

My further assumption is that the handle would be released when the thread exited. I'm basing that on the fact that in the current code, while we do "close()" the handle before the fork, we also open it again ca. line 396 and then don't do anything with it.

I can close it earlier in the parent thread, but was worried about the fact that it's taken as a global in getNumberOfJobsToQueue().

2021-07-09 18:35 UTC, righdforsa commented on bin/BedrockWorkerManager.php
> +                            $stats->benchmark('bedrockWorkerManager.db.write.insert', function () use ($localDB, $job, $safeJobName, $safeRetryAfter, $myPid) {
I was just following the extant pattern. I hate the "use" statement, personally. Can you clarify what the arrow function would look like?

2021-07-09 19:13 UTC, righdforsa commented on bin/BedrockWorkerManager.php
> +                        $localDB = new LocalDB($pathToDB, $logger, $stats);
To be clear, `$localDB` does work from inside the thread. I had assumed that the handle would be shared between all the threads, and thus would create issues if we were running "open()" and "close()", or relying on the "get last inserted row id" capability inside the threads.

2021-07-12 09:27 UTC, iwiznia commented on bin/BedrockWorkerManager.php
> +                        $localDB = new LocalDB($pathToDB, $logger, $stats);
> My assumption had been that by re-instantiating $localDB after the fork, I would get a new local db handle in the local (thread) scope.

Yes, that's correct, what is confusing me is what happens if you overwrite the same variable as in the parent thread, but thinking more about it, I doubt you can modify the variable in the parent thread.

Anyway, I think this is correct and if it is not, we'll know when we deploy it 😄

2021-07-12 09:28 UTC, iwiznia commented on bin/BedrockWorkerManager.php
> +                            $stats->benchmark('bedrockWorkerManager.db.write.insert', function () use ($localDB, $job, $safeJobName, $safeRetryAfter, $myPid) {
It would be cleaner and would not need the use, check the docs [here](https://www.php.net/manual/en/functions.arrow.php)

2021-07-12 09:29 UTC, iwiznia submitted a review, later dismissed

2021-07-12 17:16 UTC, flodnv commented on bin/BedrockWorkerManager.php
> +        workerPID integer,
So should we make this NOT NULL??

2021-07-14 18:56 UTC, righdforsa commented on bin/BedrockWorkerManager.php
> +        workerPID integer,
K, updated.

2021-07-14 18:56 UTC, righdforsa commented on bin/BedrockWorkerManager.php
> +                            $stats->benchmark('bedrockWorkerManager.db.write.insert', function () use ($localDB, $job, $safeJobName, $safeRetryAfter, $myPid) {
Hmm, I tried a simple replacement of `function () use (x) {` to `fn() => {` and got PHP fatals/syntax errors for "unexpected {". Skipping for now.

2021-07-14 19:05 UTC, righdforsa commented
Added "NOT NULL" to the workerPID column, and added deploy steps to the description. Please review both.

2021-07-15 10:46 UTC, iwiznia approved these changes

2021-07-15 10:47 UTC, iwiznia commented
Don't forget to create the version

2021-07-15 11:11 UTC, flodnv approved these changes

2021-07-19 21:44 UTC, righdforsa commented
> Don't forget to create the version

Do you mean the github release? Oops, I did that when I used the script as I was getting ready to submit the PR.

2021-07-19 21:59 UTC, righdforsa commented
Column addition queries for buddy-check:
```
ALTER TABLE localJobs ADD COLUMN workerPID integer
ALTER TABLE localJobs ADD COLUMN retryAfter text
```

2021-07-19 22:09 UTC, justinpersaud commented
👍🏽

2021-07-19 22:55 UTC, righdforsa commented
Updated all jobs dbs, checked for any issues, didn't find any. This should be good to go out. Merging.

2021-07-19 22:55 UTC, merged

2021-07-20 11:09 UTC, iwiznia commented
> Do you mean the github release? Oops, I did that when I used the script as I was getting ready to submit the PR.

I mean the tag, which is what's used to install in the other repos. This should've not have been merged, since you did not re-create the branch, so now the version is not pointing to the latest commit in this branch

2021-07-20 17:47 UTC, righdforsa commented
> > Do you mean the github release? Oops, I did that when I used the script as I was getting ready to submit the PR.
> 
> I mean the tag, which is what's used to install in the other repos. This should've not have been merged, since you did not re-create the branch, so now the version is not pointing to the latest commit in this branch

Ah, that's easy enough to fix. Tag updated to the current latest commit edca521 https://github.com/Expensify/Bedrock-PHP/releases/tag/1.9.1