store response object not closure
Expensify/Bedrock-PHP pull request #188
Opened 2022-06-17 18:22 UTC by righdforsa

I had to do this to get the code working properly. Without this, it was throwing an exception "Unable to call method getCode() on Closure object" or something similar. Might have something to do with me using PHP 8.1?

2022-06-17 19:44 UTC, iwiznia requested changes
I don't understand this change nor the error you were getting. This seems wrong to me, since benchmark is returning what the closure returns and the closure is returning a `Response` object, not a callable.
Maybe you can include your whole error here so we can look at it.
Also, keep in mind that `getStats` returns the stats object you configured, so maybe you configured it a wrong stats object? Or are you using the default NullStats?

2022-06-17 19:46 UTC, iwiznia commented
Ohhhh NullStats is wrong. [Here](https://github.com/Expensify/Bedrock-PHP/blob/main/src/Stats/NullStats.php#L15) it should do `return $function();`

2022-06-17 19:49 UTC, deetergp requested changes
Also, your commit is unsigned/unverified.

2022-06-24 21:17 UTC, righdforsa commented on src/DB.php
> +        })();
Definitely public.
![Screen Shot 2022-06-24 at 21 17 04](https://user-images.githubusercontent.com/1656127/175673799-6d7e7726-470b-417a-b5ae-64ebeb3289d6.png)

2022-06-24 21:19 UTC, righdforsa commented
> Ohhhh NullStats is wrong. [Here](https://github.com/Expensify/Bedrock-PHP/blob/main/src/Stats/NullStats.php#L15) it should do `return $function();`

Yeah, I had to do that in a previous version of the code, but in a fresh install I didn't. Wasn't quite sure what to make of that. Happy to resolve your request for changes. Looks like we have no integration tests for this repo. Might be an interesting project. :)

2022-06-24 21:23 UTC, iwiznia commented
> Looks like we have no integration tests for this repo. Might be an interesting project. :)

heh yeah, we never set them up. Not sure how valuable they will be though, as we would not really want to test bedrock itself.

2022-06-24 21:24 UTC, righdforsa commented
> Also, your commit is unsigned/unverified.

Thanks, new key. Fixed.

2022-06-24 21:25 UTC, righdforsa commented
> Not sure how valuable they will be though, as we would not really want to test bedrock itself.

Not sure what you mean. Wouldn't we want to confirm for the community that they work with the current version of Bedrock? Anyway, if it was just unit tests, that would be a start, right?

2022-06-24 21:29 UTC, iwiznia commented
> Not sure what you mean. Wouldn't we want to confirm for the community that they work with the current version of Bedrock?

I guess we could.

>  Anyway, if it was just unit tests, that would be a start, right?

Yep, but I guess that's even harder to write. 

Of course I would welcome both types of tests if you want to add them.

2022-06-24 22:01 UTC, righdforsa commented
Updated. My local testing showed this works. Thanks for helping me put the fix in the right place @iwiznia

2022-06-24 22:02 UTC, iwiznia approved these changes

2022-06-28 15:48 UTC, deetergp commented on src/DB.php
> +        })();
`:facepalm:`

2022-06-28 15:48 UTC, deetergp approved these changes

2022-06-28 15:49 UTC, merged